1task
MironenkoNadiia/node-hw1 pull request #1
Opened 2021-04-25 19:28 UTC by MironenkoNadiia

[](url)

2021-04-28 06:44 UTC, SergeiKBB requested changes

2021-04-28 06:44 UTC, SergeiKBB commented on contacts.js
> +        const contacts = await fs.readFile(contactsPath, 'utf-8', (error) => {
Почему здесь используются 2 подхода? async await и callback? Нужно использовать что-то одно

2021-04-28 06:44 UTC, SergeiKBB commented on contacts.js
> +        const contactById = contacts.find(({ id }) => id === contactId)
Эта перемена где-то используеться? Я не вижу, хотя было бы хорошо её использовать для проверки, что контакты с таким айди есть, в противном случае нам нету смысла делать фильтрацию и перезаписывать файл

2021-04-29 20:34 UTC, MironenkoNadiia commented on contacts.js
> +        const contacts = await fs.readFile(contactsPath, 'utf-8', (error) => {
async function parseContacts() {
        const contacts = await fs.readFile(contactsPath, 'utf-8', (error) => {
            if (error) {
                console.error(error.message)
                return
            };
        });
        return JSON.parse(contacts);
    }

2021-04-29 20:34 UTC, MironenkoNadiia commented on contacts.js
> +        const contactById = contacts.find(({ id }) => id === contactId)
console.table(contactById);

2021-04-30 19:35 UTC, SergeiKBB requested changes

2021-04-30 19:35 UTC, SergeiKBB commented on contacts.js
> +        console.table(contactById);
зачем здесь этот вывод в консоль? Эта функция должна отображать только список контактов.

2021-04-30 19:35 UTC, SergeiKBB commented on contacts.js
> +            if (error) {
Надо было удалить колбек. Колбеки это старая и не всегда полезная вещь (точнее они иногда могут быть полезные). Но если есть возможность использовать async await то лучше их использовать вместо колбеков

2021-05-01 10:19 UTC, MironenkoNadiia commented on contacts.js
> +            if (error) {
здравствуйте,Вы имели ввиду так?async function parseContacts() {
    try {
        const contacts = await fs.readFile(contactsPath, 'utf-8', (error))
        return JSON.parse(contacts);
    } catch (error) {
        console.error(error.message)
    }
    } 
что-то я совсем запуталась....

2021-05-01 10:49 UTC, MironenkoNadiia commented on contacts.js
> +            if (error) {
здравствуйте, так?
async function parseContacts() {
    try {
        const contacts = await fs.readFile(contactsPath, 'utf-8')
        
        return JSON.parse(contacts);
    } catch (error) {
        console.error(error.message)
    }
    }

2021-05-01 10:50 UTC, MironenkoNadiia commented on contacts.js
> +            if (error) {
здравствуйте, так?
async function parseContacts() {
    try {
        const contacts = await fs.readFile(contactsPath, 'utf-8')
         return JSON.parse(contacts);
    } catch (error) {
        console.error(error.message)
    }
    }

2021-05-01 11:54 UTC, MironenkoNadiia commented on contacts.js
> +        console.table(contactById);
async function removeContact(contactId) {
  try {
    const contacts = await parseContacts();
      const contactById = contacts.find(({ id }) => id === contactId);
      const filteredContacts = contacts.filter(({ id }) => id !== contactId);
      console.log(contactId);
    if (!contacts.includes(contactById)) {
      console.log("Контакта с таким id нет.");
    } else {
      await fs.writeFile(contactsPath, JSON.stringify(filteredContacts));
      console.log("Контакт успешно удалён.");
    }
    await fs.writeFile(contactsPath, JSON.stringify(filteredContacts, null, 2));

    console.table(filteredContacts);
  } catch (error) {
    console.log(error.message);
  }
}

больше в голову ничего не приходит

2021-05-03 08:48 UTC, SergeiKBB approved these changes

2021-05-03 11:49 UTC, merged